name: client_rest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: any

flutter:
  uses-material-design: true
